android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Consolidate memory for GitHub Actions by running Kotlin in-process (runners have 7GB RAM max)
org.gradle.jvmargs=-Xmx5632m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
kotlin.compiler.execution.strategy=in-process

org.gradle.workers.max=2
org.gradle.daemon.idleTimeout=60000
android.enableR8.fullMode=false
