android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Adjust memory for GitHub Actions (runners have 7GB RAM max)
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError

org.gradle.workers.max=2
org.gradle.daemon.idleTimeout=60000
android.enableR8.fullMode=false
